[test-groups]
integration = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'binary_id(sandhole::integration)'
test-group = 'integration'

[profile.nix]
default-filter = 'not test(/login/) - binary_id(sandhole::integration)'
